GET http://localhost:5000/api/collections
###
GET http://localhost:5000/api/products
###
GET http://localhost:5000/api/test

###
GET http://localhost:5000/api/products/67651fb223686231ab88e97s


###


###
DELETE http://localhost:5000/api/products/674d7689496c97689b4ed904


###

###

GET http://localhost:5000/api/orders 

###

POST  http://localhost:5000/api/categories
Content-Type: application/json

{
  "name"  : "Áo bolo" 
}

###
GET  http://localhost:5000/api/categories

###
GET http://localhost:5000/api/dashboard/